### ISSUE TITLE
Passcode persists between app installs

### ISSUE THREAD

**Issue by pouriaalmassi** [venmo/VENTouchLock#78]
A passcode set by the user will persist after the user has removed the app and reinstalled. In effect this means that someone who removes the app then reinstalls at a later time will be presented with the lock screen and is required to enter the original password. 

#### Steps to reproduce
1. Given an app that has implemented VENTouchLock set up a passcode.
1. Remove the app. 
1. Re-install the app. 
1. Re-launch newly installed app. 

#### Expected Behavior
- User should not be prompted for passcode set in a previous install. 

#### Actual Behavior
- User should is prompted for passcode set in a previous install.

**Comment by ericlewis** [comment]
+1

**Comment by dasmer** [comment]
This is actually expected behavior. On the Venmo app, we don't log you out if you delete the app either. It's particularly annoying to re-log into all your apps after updating to a new iPhone and thats why keychain via iCloud is great.

We persist your passcode so that a malicious user cannot delete your app and reinstall it to bypass the passcode

**Comment by ericlewis** [comment]
@dasmer that makes a ton of sense. You just gave us some extra work, thank you :)

**Comment by ericlewis** [comment]
expected behavior
