### ISSUE TITLE
Doesn't work on iOS 10

### ISSUE THREAD

**Issue by daliadanila** [venmo/VENTouchLock#80]
After setting the passcode, if user wants to show or delete the passcode, it says passcode is not set. Works fine on previous iOS versions.

**Comment by daliadanila** [comment]
The problem seems to be with SSKeychain that doesn't return the saved password.

**Comment by Liampronan** [comment]
any chance you're using the simulator? I ran into this issue on an iOS 10 simulator and was able to fix it using after coming across the following SO post (seems like a lot of people ran into that): http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator

on a tangentially related note, the SSKeychain dependency used in this library has a naming conflict in iOS10 (issue here: https://github.com/soffes/SAMKeychain/issues/154) due to a new StoreServices.framework class in iOS 10 with the same name (https://github.com/nst/iOS-Runtime-Headers/blob/master/PrivateFrameworks/StoreServices.framework/SSKeychain.h) -- I didn't see any errors related to that but it prints out a scary warning. Thoughts on a PR to update the SSKeychain pod to use SAMKeychain? I'm happy to submit one

**Comment by daliadanila** [comment]
Keychain sharing setting fixed the problem.  Thanks for that!

Thumbs up for changing to SAMKeychain. Probably a matter of time till the warning will become a crash in future iOS releases.
